apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/gitea
  prune: true
  dependsOn:
    - name: cert-manager-config
    - name: cnpg-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dawarich
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./dawarich
  prune: true
  dependsOn:
    - name: cert-manager-config
    - name: cnpg-operator
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wireguard
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./wireguard
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./homepage
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freegamesbot
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./freegamesbot
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./media
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filestash
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./filestash
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./jellyseerr
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cividle
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cividle
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yopass
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./yopass
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./vaultwarden
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./uptime-kuma
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stremio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./stremio
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./opencloud
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: technitium
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./technitium
  prune: true
  dependsOn:
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: gitea-apps
    namespace: flux-system
  wait: true
  timeout: 10m0s
