apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitea-apps
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@git.meneerak.nl/flux/apps.git
  ref:
    branch: main
  secretRef:
    name: gitea-apps-auth   # created manually, see below
