apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dawarich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:17.10-3.6.4-202608031108-system-trixie@sha256:e3f5affa754f65a4d703dc6a2f2f37233250bbc1fe2a4ae84ae3a828249b0b97
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: dawarich
      owner: dawarich
      secret:
        name: postgresql-auth   # created manually, see below
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
