apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: zitadel
spec:
  instances: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  storage:
    size: 10Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: postgresql-auth